In [1]:
import torch 
import pandas as pd 

In [2]:
scalar=torch.tensor(3.0)
vector=torch.tensor([1.0,2.0,3.0])
matrix=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
tensor3d=torch.tensor([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])

In [3]:
scalar

tensor(3.)

In [4]:
vector

tensor([1., 2., 3.])

In [5]:
matrix

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
tensor3d

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

note -> https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor with shape (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1307, 0.4966, 0.7607, 0.9186],
        [0.1496, 0.8921, 0.7698, 0.1567],
        [0.8997, 0.9783, 0.8710, 0.8282]])

In [8]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size=torch.rand(224,223, 3) # height, width, color channels
random_image_size.shape, random_image_size.ndim,

(torch.Size([224, 223, 4]), 3)